Repository muhilkennedy/Learning-App-WebShopping, pull requests merged in 2020-10, with the labels that each got.

#57 bug fixes
  admin-ui/src/app/shared/product/product.service.ts
  admin-ui/src/app/views/dashboard/components/todo/todo.component.html
  admin-ui/src/app/views/dashboard/components/todo/todo.component.ts
  admin-ui/src/app/views/pos/pos.component.html
  admin-ui/src/app/views/pos/pos.component.ts
  admin-ui/src/app/views/product/manage-products/manage-product/manage-product.component.html
  admin-ui/src/app/views/product/manage-products/manage-product/manage-product.component.ts
  admin-ui/src/app/views/product/product-list/product-list.component.html
  backendParent/api/src/main/java/com/backend/api/controller/ProductController.java
  backendParent/core/src/main/java/com/backend/core/dao/TenantDao.java
  backendParent/persistence/src/main/java/com/backend/persistence/dao/EmployeeDao.java
  backendParent/persistence/src/main/java/com/backend/persistence/dao/PosDao.java
  backendParent/persistence/src/main/java/com/backend/persistence/dao/ProductDao.java
  backendParent/persistence/src/main/java/com/backend/persistence/serviceImpl/ProductServiceImpl.java
  backendParent/service/src/main/resources/db/migration/V1__initial.sql
  backendParent/service/src/main/resources/db/migration/V2__initial.sql
Labels: bug, muhil

#58 sql bug fix
  backendParent/service/src/main/resources/db/migration/V1__initial.sql
Labels: bug

#59 barcode changes
  admin-ui/config.xml
  admin-ui/package.json
  admin-ui/src/app/app.component.css
  admin-ui/src/app/app.module.ts
  admin-ui/src/app/containers/chat-messenger/chat-messenger.component.html
  admin-ui/src/app/containers/chat-messenger/chat-messenger.component.ts
  admin-ui/src/app/service/websocket/message.ts
  admin-ui/src/app/service/websocket/socket.service.ts
  admin-ui/src/app/shared/product/product.service.ts
  admin-ui/src/app/views/pos/pos.component.html
  admin-ui/src/app/views/pos/pos.component.ts
  admin-ui/src/app/views/pos/pos.module.ts
  backendParent/api/src/main/java/com/backend/api/controller/ProductController.java
  backendParent/api/src/main/java/com/backend/api/stomp/configuration/WebSocketConfig.java
  backendParent/api/src/main/java/com/backend/api/stomp/controller/StompController.java
  backendParent/core/src/main/java/com/backend/core/security/RealmFilter.java
  backendParent/persistence/src/main/java/com/backend/persistence/repository/ProductRepository.java
  backendParent/persistence/src/main/java/com/backend/persistence/service/ProductService.java
  backendParent/persistence/src/main/java/com/backend/persistence/serviceImpl/ProductServiceImpl.java
Labels: enhancement, muhil

#63 pos enhancements
  admin-ui/src/app/containers/default-layout/default-layout.component.html
  admin-ui/src/app/containers/default-layout/default-layout.component.ts
  admin-ui/src/app/shared/pos/PosProduct.ts
  admin-ui/src/app/shared/pos/pos.service.ts
  admin-ui/src/app/views/invoice/invoice-template.component.html
  admin-ui/src/app/views/pos/pos.component.html
  admin-ui/src/app/views/pos/pos.component.ts
  backendParent/api/src/main/java/com/backend/api/admin/controller/POSController.java
  backendParent/api/src/main/java/com/backend/api/controller/ProductController.java
  backendParent/core/src/main/java/com/backend/core/util/DBUtil.java
  backendParent/core/src/main/java/com/backend/core/util/TenantUtil.java
  backendParent/persistence/src/main/java/com/backend/persistence/dao/PosDao.java
  backendParent/persistence/src/main/java/com/backend/persistence/helper/POSData.java
  backendParent/persistence/src/main/java/com/backend/persistence/serviceImpl/POSServiceImpl.java
Labels: enhancement, muhil

#68 product edit
  admin-ui/src/app/_nav.ts
  admin-ui/src/app/containers/default-layout/default-layout.component.html
  admin-ui/src/app/containers/default-layout/default-layout.component.ts
  admin-ui/src/app/shared/product/product.service.ts
  admin-ui/src/app/views/employee/employee-permission/employee-permission.component.ts
  admin-ui/src/app/views/pos/pos.component.html
  admin-ui/src/app/views/pos/pos.component.ts
  admin-ui/src/app/views/product/product-edit/product-edit.component.css
  admin-ui/src/app/views/product/product-edit/product-edit.component.html
  admin-ui/src/app/views/product/product-edit/product-edit.component.spec.ts
  admin-ui/src/app/views/product/product-edit/product-edit.component.ts
  admin-ui/src/app/views/product/product-list/product-list.component.css
  admin-ui/src/app/views/product/product-list/product-list.component.html
  admin-ui/src/app/views/product/product-list/product-list.component.ts
  admin-ui/src/app/views/product/product-routing.module.ts
  admin-ui/src/app/views/product/product.module.ts
  admin-ui/src/app/views/task/task.component.ts
  backendParent/api/src/main/java/com/backend/api/controller/ProductController.java
  backendParent/commons/src/main/java/com/backend/commons/util/CommonUtil.java
  backendParent/persistence/src/main/java/com/backend/persistence/dao/ProductDao.java
  backendParent/persistence/src/main/java/com/backend/persistence/entity/Product.java
  backendParent/persistence/src/main/java/com/backend/persistence/repository/ProductImagesRepository.java
  backendParent/persistence/src/main/java/com/backend/persistence/repository/ProductRepository.java
  backendParent/persistence/src/main/java/com/backend/persistence/service/ProductService.java
  backendParent/persistence/src/main/java/com/backend/persistence/serviceImpl/ProductServiceImpl.java
  backendParent/service/src/main/resources/db/migration/V1__initial.sql
Labels: feature, muhil
