Repository muhilkennedy/Learning-App-WebShopping, pull requests merged in 2021-01, with the labels that each got.

#103 Mani ref2
  backendParent/Dockerfile
  backendParent/docker-cmd
  backendParent/docker-cmd.txt
  backendParent/docker-compose.yml
Labels: devops, mani

#111 bug fix
  admin-ui/.firebase/hosting.d3d3.cache
  admin-ui/.firebaserc
  backendParent/persistence/src/main/java/com/backend/persistence/dao/ProductDao.java
  backendParent/persistence/src/main/java/com/backend/persistence/service/InvoiceService.java
  backendParent/persistence/src/main/java/com/backend/persistence/serviceImpl/InvoiceServiceImpl.java
  backendParent/service/src/main/resources/Tenant.properties
  backendParent/service/src/main/resources/invoiceTemplate/Invoice-Template.docx
  client-ui-angular/src/app/app.module.ts
  client-ui-angular/src/app/components/checkout/checkout.component.html
  client-ui-angular/src/app/components/home/home.component.html
  client-ui-angular/src/app/components/login/login.component.html
  client-ui-angular/src/app/components/product-list/product-list.component.html
  client-ui-angular/src/app/components/profile/profile.component.html
  client-ui-angular/src/app/components/shared/footer/footer.component.html
  client-ui-angular/src/assets/images/home/map.png
  client-ui-angular/src/assets/images/home/map_world.png
  client-ui-angular/src/environments/environment.ts
Labels: bug, muhil

#115 image compression change
  backendParent/api/src/main/java/com/backend/api/admin/controller/HomeMediaController.java
  backendParent/api/src/main/java/com/backend/api/admin/controller/ProductAdminController.java
  backendParent/commons/src/main/java/com/backend/commons/util/CommonUtil.java
  backendParent/core/src/main/java/com/backend/core/security/RealmFilter.java
  backendParent/persistence/src/main/java/com/backend/persistence/serviceImpl/ProductServiceImpl.java
  client-ui-angular/.firebase/hosting.d3d3.cache
  client-ui-angular/www/index.html
  client-ui-angular/www/main.34850d4a9ab673233a9e.js
  client-ui-angular/www/main.8278454f04413c2972d3.js
  client-ui-angular/www/styles.6169e902d4d17fdd46ae.css
Labels: enhancement, muhil
